lib/puppet_x/sqlserver/features.rb
spec/acceptance/sqlserver_instance_spec.rb

Fix issues with idempotency as a result of the changes in 2.0.1 to retrieve facts information from registry instead of WMI. Also updates acceptance tests to validate idempotency. Increases the test tier for changed tests to `high` per @ThoughtCrhyme's suggestion.
Supersedes #249 which was accidentally based on a branch on upstream instead of my fork. 🤦‍♂️

(MODULES-6022) Make SQLServer Instance Idempotent Again

---

lib/puppet_x/sqlserver/features.rb

This change updates the features.rb file to ensure that it is checking for the registry keys for SQL 2017.

(MODULES-6168) Detect SQL 2017

---

CHANGELOG.md
metadata.json

Release prep for version 2.1.0

(MODULES-6239) prep for 2.1.0 release

---

lib/puppet/provider/sqlserver_instance/mssql.rb
spec/acceptance/sqlserver_instance_spec.rb
spec/spec_helper_acceptance.rb
spec/unit/puppet/provider/sqlserver_instance_spec.rb

As described in MODULES-2904, installation fails with an array of SQL Admins. This was fixed in the use_discrete=true block (line 171-178. However the double quotes also needed to be removed from the list of accounts for the /SQLSYSADMINACCOUNTS switch parameter. 
This PR removes the double quotes in the use_discrete=true section (which is only used for /SQLSYSADMINACCOUNTS). I have tested this to sucessfully fix installation for the following scenario's:
- SQL 2016 on Win2016 with 1 local group specified for SQLSYSADMINACCOUNTS
- SQL 2016 on Win2016 with 1 domain group specified for SQLSYSADMINACCOUNTS
- SQL 2016 on Win2016 with 3 groups (1 local, 1 domain and BUILTIN\Administrators) specified for SQLSYSADMINACCOUNTS
Without the fix, the only setting that works is …

(MODULES-6356) Fixes a problem still remaining from MODULES-2904

---

.sync.yml
CONTRIBUTING.md

Previosuly the contributing document was excluded from modsync.  This commit
enables the contributing document to be managed by modsync and adds the current
document as of commit f0c21975ec for the modsync configs.

(FM-6605) Add CONTRIBUTING.MD to repository

---

CHANGELOG.md

This commit updates the changelog format to the more standardized KAC
format: http://keepachangelog.com/en/1.0.0/
Ticket numbers were added to comments in the cases where they could be
found.

(DOCUMENT-824) Update Changelog Format

---

CHANGELOG.md
lib/puppet_x/sqlserver/sql_connection.rb
spec/acceptance/sqlserver_tsql_spec.rb
spec/unit/puppet_x/sql_connection_spec.rb

The sqlserver_tsql resource does not handle errors returned from T-SQL
statements properly. The errors come back from the query but unless the
phrase 'SQL Server' was included in the error text, the error was not
then passed back to the user/logs. This change ensure that errors
returned are passed back properly by inspecting the Errors property of
the ADO object used to run the query. Note that this may not behave as
expected if the error that occurrs is of sufficently low severity that a
rowset, even if empty, is also returned. If a rowset is returned by the
ADO object, the object will not populate the Errors property, and there
is no way to tell a low severity error occurred. For instance 'Select
1/0' returns a low severity division by zero error, and an empty rowset.
Because the empty …

(MODULES-6281) Return Errors from T-SQL

---

CHANGELOG.md

This commit fixes the markdown link to MODULES-6339 explaining why the
command to update bundle was removed from TRAVISCI builds.

(MAINT) Fix Changelog Link

---

spec/spec_helper.rb
spec/unit/puppet_x/sql_connection_spec.rb

- Prior code from 9b8a0fe used a non-obvious
behavior in the mocking framework to return the Description value from an
error instance.
If the count of errors was returned was increased by 1, the code would be
subtly wrong as mocks are generating to each call of .Errors(x) with the
supplied values.
- Instead, more clearly mock the actual code path, and additionally provide
two separate messages, demonstrating they are iterated and joined properly

(maint) Spec fixes

---

lib/puppet_x/sqlserver/features.rb

Add logical OR to registry subkey check for installed features

MODULES-7734 Detect installed features with value greater than 1

---

CHANGELOG.md
README.md
lib/puppet/provider/sqlserver_features/mssql.rb
lib/puppet/provider/sqlserver_instance/mssql.rb
lib/puppet/type/sqlserver_instance.rb
lib/puppet_x/sqlserver/features.rb
lib/puppet_x/sqlserver/server_helper.rb
metadata.json
spec/spec_helper_acceptance.rb

This change allows the module to install and uninstall SQL 2019
idempotently. No further support is implemented.

(MODULES-8438) Install 2019

---

spec/acceptance/z_last_sqlserver_features_spec.rb
spec/spec_helper_acceptance.rb

This PR fixes tests to look for ISO files in Artifactory instead of the older int-resources server. That server went away, and the testing resources had to be moved to the Artifactory server so that Jenkins Acceptance test pipelines can start running again.
This change also fixes a bug in the acceptance tests where the wrong set of features was being verified for sqlserver 2016. Sqlserver 2016 will not install Connectivity tools in the scenario being tested. This is due to a change in that version of SQL Server, not a mal function in the module code.

(MAINT) Migrate test resources to artifactory - Fix Pipelines.

---

README.md
tasks/get_sql_logins.json
tasks/get_sql_logins.ps1
tasks/set_sql_logins.json
tasks/set_sql_logins.ps1

Add a set of tasks for ad hoc management of SQL Logins. These tasks
gather information about the current state of logins on an instance and
then will allow the user to set properties of a specific user on an
instance.
Scenarios for this might be a dba that usually has the SA login disabled
might want to enable it momentarily for a specific task, and then
disable it again.
It can also be used to ensure that the state of users, like a disabled
SA account are in the state a dba expects them to be in.

(MODULES-8606) Add SQL Logins Tasks

---

CHANGELOG.md
manifests/role.pp
manifests/role/permissions.pp
spec/acceptance/sqlserver_role_spec.rb
spec/defines/role/permissions_spec.rb
spec/defines/role_spec.rb

Due to the lack of interpolating the `$title` of a defined type within the resources that it contains we have a duplication declaration under the following scenario:
*"I want to manage the members of the data_writer role on both instance 1 and instance 2".*

(MODULES-8677) Made resource title unique among many instances

---

CHANGELOG.md
spec/acceptance/sqlserver_login_spec.rb
templates/query/login_exists.sql.erb

This means that `ensure => absent` actually works for logins

(MODULES-8685) Changed END to be in the same conditional as BEGIN

---

README.md

This commit makes minor edits to the README.

(MODULES-8721) README edit

---

CHANGELOG.md
README.md
tasks/start_sql_agent_job.json
tasks/start_sql_agent_job.ps1

This commit adds a Bolt task allowing users to start SQLServer agent
jobs on remote SQL Instances. The user can choose to start jobs at any
step, and they can choose to wait for the job to complete before
returning, or to return data immediately and let the jobs run async.

(MODULES-8610) Add start agent job task

---

files/shared_task_functions.ps1
tasks/get_sql_logins.json
tasks/get_sql_logins.ps1
tasks/get_sqlagent_jobs.json
tasks/get_sqlagent_jobs.ps1
tasks/set_sql_logins.json
tasks/set_sql_logins.ps1
tasks/start_sql_agent_job.json
tasks/start_sql_agent_job.ps1

There was a large amount of repeated code in the tasks being added to
the module. This change refactors the shared code into a file that is
loaded into each task as it runs to cut down on the repetition of code.

(MAINT) Refactor tasks to use shared code file

---

tasks/start_sql_agent_job.json
tasks/start_sql_agent_job.ps1

Prior to this change, even though the job_name param is defined as
required by the PowerShell script that powers the task, the json file
that describes the task defines that parameter to Bolt as Optional.
This causes the task to hang if the task is invoked with no job_name
parameter. This change updates the json so that Bolt understands the
param is required, and removes an unnecessary conditional check to
to ensure the paramter is present, as both platforms already ensure
it. The else block in that check also had code that should never run
in this task.

(MODULES-8749) Make job_name param required.

---

tasks/start_sql_agent_job.ps1

The wait parameter in the start_sql_agent_job depends on a sleep
interval that waits long enough for the agent to spool up a job and get
it running.
In testing it appears that some agent jobs are not spinning up fast
enough, causing the wait parameter to have no effect. This change
increased the timeout so that the wait parameter has time to see the
job starting to execute and then wait for it to complete.

(MAINT) Increase timeout interval

---

README.md

A user trying to follow our advanced example ran into an issue. The
example as written is only suitable for setups that are using local
accounts, not domain accounts. They also found that the Facter fact
`domain` returns the FQDN of the domain, which is not suitable for
contsructing user names in the `netbiosname\username` format.
This change adds a clarification to the example that the example is only
usable when using local group, and given that there is no `netbiosname`
fact available, provides a suggestion for one way to work around the
issue.

(MODULES-7553) Add Example Clarification

---

CHANGELOG.md
manifests/sp_configure.pp
metadata.json
spec/defines/sp_configure_spec.rb
spec/spec_helper_acceptance.rb
templates/restart_service.ps1.erb

Prviously, the sp_configure.pp file would attempt to use the builtin
service resource to restart the MSSQLServer service if a configuration
change was made. This attempt would fail if there was a dependent
service such as the SQL Agent service, which is extremely common.
This change implements an extremely small PowerShell script instead to
force restart the MSSQLSERVER service, even if there are dependent
services.
In testing this resulted in the Agent service going down and then
coming back up as expected.

(MODULES-6904) Restart SQL Server Service with Dependent Services

---

metadata.json

The issues link points at an area in Jira that no longer exists. This
change fixes it to point at a more generic place that will allow users
to createa a ticket.

(MODULES-9472) Fix Issues Link

---

manifests/role/permissions.pp
templates/create/login/permission.sql.erb
templates/create/role/permissions.sql.erb
templates/create/user/permission.sql.erb
templates/query/login/permission_exists.sql.erb
templates/query/role/permission_exists.sql.erb
templates/query/user/permission_exists.sql.erb

Prior to this change, some ERB templates would cause jruby errors
on the master during catalog compilation. The templates contained code
that would attempt to modify the value of a frozen string.
This change modifies the template code to ensure that no frozen string
values are attempted to be modified.
It also makes slight fixes to the syntax in the templates to ensure that
each instance of this pattern is written more consistantly.

(MODULES-9912) ERB Template Errors

---

.sync.yml
metadata.json

The `.sync.yml` was not updated to maintain a number of Rubocop fixes made during this PR: https://github.com/puppetlabs/puppetlabs-sqlserver/pull/326
This ensures that a `pdk update` will not overwrite those changes and cause subsequent PRs to fail Rubocop checks.

(maint) Update .sync.yml for Rubocop fixes

---

README.md

Add a note to the README's Limitations section that SSMS must be
installed separately since SQL Server 2016, which moved SSMS to
its own installer.
This does not satisfy the other criteria of MODULES-6585
(implement and test failure modes when passing SSMS as a feature).

(MODULES-6585) Note that SSMS is installed separately in 2016+

---

spec/acceptance/z_last_sqlserver_features_spec.rb

SSMS is installed separately starting with SQL Server 2016. Update
a test to omit SSMS from feature support checks from 2016 and
newer, rather than only 2016. See also MODULES-6585.

(maint) Update test checking SSMS feature compatibility

---

.sync.yml
.travis.yml
Rakefile
appveyor.yml
metadata.json
spec/spec_helper.rb

"(IAC-365) updating tokens and dataset for honeycomb"
pdk version: `1.16.0`

(IAC-365) updating tokens and dataset for honeycomb

---

lib/puppet/property/sqlserver_tsql.rb
spec/acceptance/sqlserver_tsql_spec.rb
spec/unit/puppet/property/tsql_spec.rb

The previous commit that improved T-SQL error handling was incomplete.
That commit (9b8a0fe9bbbe0699b6626f92ac6f9dc4ddad9584) was not able to
overcome an important issue.
The issue was that if there was a successfull row insert into a table
the `Errors` collection of the ADODB.Connection would be empty, even
if an error was deliberately thrown using the `THROW` keyword.
It turns out that the successfull row insert was causing a text return
value, and it's a known issue that if values are returned to the object
that the Errors collection will be empty.
We know now that turning `SET NOCOUNT ON` in the beginning of the query
will suppress that text status message and allow more errors to be
properly detected in the ADODB.Connect object, and handled properly
in the module's `onlyif` clause.

(FM-8879) Handle T-SQL Errors Properly

---

lib/puppet/provider/sqlserver_features/mssql.rb

Seems as if the check on whether Dotnet installation is necessary and the feature source pass where accidentally separated from the install method call.

(MODULES-10825) - Dotnet installation fix

---

.github/workflows/spec.yml
.puppet-lint.rc
.sync.yml
Rakefile
examples/database_full.pp
examples/init.pp
examples/sp_configure.pp
lib/puppet_x/sqlserver/features.rb
manifests/config.pp
manifests/database.pp
manifests/login.pp
manifests/login/permissions.pp
manifests/role.pp
manifests/role/permissions.pp
manifests/sp_configure.pp
manifests/user.pp
manifests/user/permissions.pp
metadata.json

(Maint) PDK Update
pdk version: `2.3.0`

pdksync - (Maint) PDK Update

---

metadata.json

Prior to this release, we were preparing for a major release in several
modules, including powershell and apt. This meant that some modules that
use them as a dependency might need their metadata.json file updated to
keep working properly.
This update aims to correctly update the dependecies of the sqlserver
module so that it can keep working properly with our latest release of
our powershell module.

(CAT-136) Update dependencies

---

lib/puppet/type/sqlserver_features.rb
lib/puppet/type/sqlserver_instance.rb

Prior to this commit, using puppetlabs-sqlserver with deprecated features/tools would raise a deprecation warning messages in puppet agent runs, although the documentation says the deprecated variable is valid. This is due to a mistake in a puppet-strings run which excluded part of the documentation regarding this issue. This commit reinstate this documentation to avoid future confusion.

(CONT-370) Reinstate lost sqlserver documentation on feature & tool deprecations

---

lib/puppet/type/sqlserver_features.rb
lib/puppet/type/sqlserver_instance.rb

This PR fixes a format error due to puppet-strings by removing blank space from documentation

Fix puppet strings formatting

---

manifests/login.pp
manifests/role.pp
manifests/user.pp

Replaces instances of the deprecated 'has_key' function removed in https://github.com/puppetlabs/puppetlabs-stdlib/pull/1319

(MAINT) - Remove deprecated 'has_key'

---

.github/workflows/ci.yml
.github/workflows/nightly.yml

Prior to this commit, there were deprecation warnings in the github action workflows regarding use of checkout@v2. This commit uses v3.

(CONT-985) Address deprecation warnings

---

.github/workflows/ci.yml

Necessary change to workflow that ensures that the CI can still run on forked PRs and supply secrets. 
See https://github.com/puppetlabs/puppetlabs-lvm/pull/302
**Note the tests will not run until merged**

(maint) - update trigger in ci.yml

---

.github/workflows/ci.yml
.github/workflows/nightly.yml

Earlier acceptance tests were running always against the main branch irrespective of the PR branch or any code changes.
Add any additional context about the problem here. 
Mention any related issues or pull requests.

CAT-1208 : Fix CI to run workflow againt PR branch

---

spec/acceptance/sqlserver_config_spec.rb
spec/spec_helper_acceptance_local.rb

Fix CI to failures
Add any additional context about the problem here. 
Mention any related issues or pull requests.

CAT-1208 : Fix CI to failures
